name = "Tethers"
uuid = "9fc261b7-0902-4839-ada8-9390617e313c"
authors = ["Uwe Fechner <uwe.fechner.msc@gmail.com> and contributors"]
version = "0.2.0"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
ControlPlots = "23c2ee80-7a9e-4350-b264-8e670f12517c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Timers = "21f18d07-b854-4dab-86f0-c15a3821819a"

[compat]
Conda = "1.10.2"
CondaPkg = "0.2.23"
ControlPlots = "0.1.5"
LiveServer = "1.3.1"
ModelingToolkit = "9.28.0"
OrdinaryDiffEq = "6.87.0"
PackageCompiler = "2.1.17"
Parameters = "0.12.3"
Pkg = "=1.10.0"
Timers = "=0.1.5"
julia = "~1.10, ~1.11"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Documenter"]
